'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, AudioLines, ChevronRight, CircleHelp, SlidersHorizontal, Volume2, VolumeX, Image as ImageIcon, CloudRain, Crosshair, Download, Globe2, LayoutGrid, MapPin, Menu, Plus, Radio, RotateCcw, ShieldCheck, Users, X } from 'lucide-react';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { Toaster } from '@/components/ui/sonner';
import { AuditView, DemoDialog, ReportDialog, ResponseSheet, SignalsView, TeamsView } from '@/components/relay-views';
import { useRelay } from '@/hooks/use-relay';
import ResponseField from '@/components/response-field';
import ResponseMap from '@/components/response-map';
import { teams, categoryLabels } from '@/lib/relay';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import IncidentIntake from '@/components/incident-intake';
import OperationsDeck from '@/components/operations-deck';
import RehearsalDialog from '@/components/rehearsal-dialog';
import InteractionEffects from '@/components/interaction-effects';
import { useExperience } from '@/hooks/use-experience';
import { ExperienceSettings, PageTransition } from '@/components/experience-controls';
import RelayLogo from '@/components/relay-logo';
import CityAtmosphere from '@/components/city-atmosphere';
type View='Mission control'|'Signals'|'Responders'|'Decisions';

export default function Home(){
 const relay=useRelay(),{incidents,audit}=relay;
 const [rehearsalOpen,setRehearsalOpen]=useState(false),[settingsOpen,setSettingsOpen]=useState(false);
 const experience=useExperience<View>('Mission control'),view=experience.view;
 const viewLabels:Record<View,string>={'Mission control':'Overview',Signals:'Incidents',Responders:'Teams',Decisions:'Activity log'};
 const [selected,setSelected]=useState('RLY-1042'),[reportOpen,setReportOpen]=useState(false),[responseOpen,setResponseOpen]=useState(false),[demoOpen,setDemoOpen]=useState(false),[resetOpen,setResetOpen]=useState(false),[mapMode,setMapMode]=useState('city'),[menuOpen,setMenuOpen]=useState(false);
 const active=incidents.find(i=>i.id===selected)??incidents[0];
 const pending=incidents.filter(i=>i.status==='open'),urgent=pending.filter(i=>i.severity==='critical'),available=teams.filter(t=>!incidents.some(i=>i.status==='dispatched'&&i.teamId===t.id)),unresolved=incidents.filter(i=>i.status!=='resolved'),resolved=incidents.filter(i=>i.status==='resolved');
 const people=unresolved.reduce((n,i)=>n+i.people,0);
 const routeTeam=teams.find(t=>t.id===active.teamId);
 const selectAndReview=(id:string)=>{setSelected(id);setResponseOpen(true);};
 const navigate=(v:View)=>{setMenuOpen(false);experience.go(v);};
 const cycleIncident=(direction:number)=>{const index=incidents.findIndex(i=>i.id===active.id);setSelected(incidents[(index+direction+incidents.length)%incidents.length].id);};
 const stateRef=useRef({incidents,audit});stateRef.current={incidents,audit};
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}};register({name:'read_response_workspace',description:'Read local demo signals, team assignments, and decision count.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({mode:'local-demo',incidents:stateRef.current.incidents,decisionCount:stateRef.current.audit.length})});register({name:'open_signal_review',description:'Open the response review for a signal. Does not dispatch or resolve anything.',inputSchema:{type:'object',properties:{signalId:{type:'string'}},required:['signalId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||!('signalId' in input)||typeof input.signalId!=='string'||!stateRef.current.incidents.some(i=>i.id===input.signalId))throw new Error('Unknown signal ID');setSelected(input.signalId);setResponseOpen(true);return {opened:input.signalId,dispatched:false};}});return ()=>life.abort();},[]);
 const titles:Record<View,{title:string;accent:string;subtitle:string}>={'Mission control':{title:'When every',accent:'second counts.',subtitle:'One clear picture. One coordinated response.'},Signals:{title:'Every call.',accent:'Accounted for.',subtitle:'Search reports, check their priority, and assign a suitable team.'},Responders:{title:'Built around',accent:'the responders.',subtitle:'See each team’s skills, capacity, and current assignment.'},Decisions:{title:'Trust leaves',accent:'a trace.',subtitle:'See what happened, who could act, and why an action was allowed or blocked.'}};
 return <div className={`relay-experience ${!experience.preferences.motion?'motion-paused':''}`} data-page-phase={experience.layer?.phase??'idle'}><div className="ambient-glow glow-one"/><div className="ambient-glow glow-two"/><div className="film-grain" aria-hidden="true"/>
  <header className="command-header"><button className="brand" aria-label="Relay mission control" onClick={()=>navigate('Mission control')}><RelayLogo/></button><nav className={menuOpen?'command-nav nav-open':'command-nav'} aria-label="Workspace">{(['Mission control','Signals','Responders','Decisions'] as View[]).map((name,index)=><button key={name} onClick={()=>navigate(name)} className={view===name?'active':''} aria-current={view===name?'page':undefined}><span>0{index+1}</span>{viewLabels[name]}{name==='Signals'&&<i>{pending.length}</i>}</button>)}</nav><div className="header-tools"><button className="sound-control" aria-label={experience.preferences.sound?'Turn sound off':'Turn sound on'} aria-pressed={experience.preferences.sound} onClick={()=>experience.update({sound:!experience.preferences.sound})}>{experience.preferences.sound?<Volume2 size={17}/>:<VolumeX size={17}/>}<span>{experience.preferences.sound?'Sound on':'Sound off'}</span></button><button className="experience-toggle" aria-label="Experience settings" onClick={()=>setSettingsOpen(true)}><SlidersHorizontal size={17}/></button><span className="cedar-badge"><span/>AWS CEDAR</span><button className="header-help" aria-label="Explore the demo" onClick={()=>setDemoOpen(true)}><CircleHelp size={18}/></button><button className="report-top" aria-label="Report an incident" onClick={()=>setReportOpen(true)} disabled={!relay.ready}><Plus size={15}/><span>Report incident</span></button><button className="mobile-menu" aria-label={menuOpen?'Close navigation':'Open navigation'} onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X size={22}/>:<Menu size={22}/>}</button></div></header>
  <main aria-busy={!!experience.layer}>
  {view==='Mission control'?<section className="mission-stage view-enter" key="mission"><div className="stage-corner top-left"/><div className="stage-corner bottom-right"/>{mapMode==='city'&&<CityAtmosphere paused={!experience.preferences.motion} incident={active} index={incidents.findIndex(i=>i.id===active.id)} total={incidents.length} onPrevious={()=>cycleIncident(-1)} onNext={()=>cycleIncident(1)} onReview={()=>setResponseOpen(true)}/>}
   <div className="mission-intro"><div className="mission-kicker"><span className="status-orbit"/>COMMUNITY RESPONSE, CONNECTED<span className="kicker-line"/></div><h1 className="burn-reveal">When every<br/><em>second counts.</em></h1><p>See who needs help. Find the right team.<br/>Review, approve, and follow the response.</p><div className="mission-actions"><button className="primary-button" onClick={()=>selectAndReview(pending[0]?.id??active.id)}>Find a response team<ArrowUpRight size={18}/></button><button className="watch-demo" onClick={()=>setRehearsalOpen(true)}><span><ArrowRight size={16}/></span>Play the rehearsal</button></div><div className="mission-stats"><div><strong key={`u-${urgent.length}`}>{String(urgent.length).padStart(2,'0')}<span className="urgent-spark"/></strong><span>Urgent incidents</span></div><div><strong key={`p-${people}`}>{people}<span className="stat-unit"> people</span></strong><span>People needing help</span></div><div><strong key={`t-${available.length}`}>{String(available.length).padStart(2,'0')}</strong><span>Teams available</span></div></div></div>
   {mapMode!=='city'&&<div className="scene-shell" key={mapMode}><div className="scene-halo"/>{mapMode==='spatial'?<ResponseField incidents={incidents} selected={active.id} onSelect={selectAndReview} ambientPaused={!experience.preferences.motion}/>:<div className="geographic-stage"><ResponseMap incidents={incidents} teams={available} selected={active.id} onSelect={selectAndReview} route={active.status==='dispatched'&&routeTeam?{team:routeTeam,incident:active}:undefined}/></div>}</div>}
   <div className="scene-location"><div><span className="coordinate-cross">+</span><span>BENGALURU, IN</span><Globe2 size={14}/></div><p>12.9450° N&nbsp;&nbsp;77.6300° E</p><span className="scenario-pill"><CloudRain size={13}/>MONSOON / SAMPLE SCENARIO</span></div>
   <div className={`scene-caption ${mapMode==='city'?'city-mode-caption':''}`}><div className="scene-caption-line"/><span>{mapMode==='city'?'ILLUSTRATIVE CITY VIEW':mapMode==='spatial'?'3D PRIORITY FIELD':'NEIGHBOURHOOD MAP'}</span><p>{mapMode==='city'?'Fictional imagery. Incident details are sample reports.':mapMode==='spatial'?'Taller peaks mean higher priority, not water depth.':'Approximate neighbourhood locations. Not navigation.'}</p></div>
   <div className="scene-mode"><Tabs value={mapMode} onValueChange={setMapMode}><TabsList><TabsTrigger value="city"><ImageIcon size={14}/>City</TabsTrigger><TabsTrigger value="spatial"><AudioLines size={14}/>3D field</TabsTrigger><TabsTrigger value="map"><MapPin size={14}/>Map</TabsTrigger></TabsList></Tabs></div>
   <div className="focus-dock" key={active.id}><div className="focus-index"><span>SELECTED INCIDENT</span><strong>{String(incidents.findIndex(i=>i.id===active.id)+1).padStart(2,'0')}<span>/ {String(incidents.length).padStart(2,'0')}</span></strong></div><div className="focus-main"><div><span className={`severity ${active.severity}`}><i/>{active.severity} priority</span><span className="focus-code">{active.id}</span></div><h2>{active.title}</h2><p><MapPin size={13}/>{active.location}<span> / </span>{active.people} people<span> / </span>{categoryLabels[active.category]}<span className="focus-status">{active.status==='open'?'Needs a team':active.status==='dispatched'?'Team assigned':'Resolved'}</span></p></div><button className="focus-action" onClick={()=>setResponseOpen(true)}><span>Review response</span><ArrowUpRight size={23}/></button></div>
   <div className="stage-bottom"><span><i/>LOCAL-FIRST. HUMAN-LED. CEDAR-CHECKED.</span><span>NO LIVE EMERGENCY DATA<ArrowDown size={12}/></span></div>
  </section>:<section className="work-surface view-enter" key={view}><div className="work-title"><div><span className="mission-kicker">RELAY / {viewLabels[view].toUpperCase()}</span><h1>{titles[view].title} <em>{titles[view].accent}</em></h1><p>{titles[view].subtitle}</p></div><button className="primary-button" onClick={()=>setReportOpen(true)}><Plus size={16}/>Report an incident</button></div>{view==='Signals'?<SignalsView incidents={incidents} onSelect={selectAndReview}/>:view==='Responders'?<TeamsView incidents={incidents} onSelect={selectAndReview}/>:<AuditView audit={audit} engine={relay.engine} onExport={relay.exportSnapshot}/>}</section>}
  {view==='Mission control'&&<section className="response-guide" aria-label="How Relay works"><button onClick={()=>setReportOpen(true)}><span>01</span><div><strong>Tell us what happened</strong><small>A plain-language report becomes a reviewed incident.</small></div></button><button onClick={()=>selectAndReview(pending[0]?.id??active.id)}><span>02</span><div><strong>Find the right people</strong><small>Compare team skills, capacity, and availability.</small></div></button><button onClick={()=>navigate('Decisions')}><span>03</span><div><strong>Approve. Act. Keep track.</strong><small>Human approval, policy checks, and a clear history.</small></div></button></section>}<section className="signal-stream"><div className="stream-heading"><div><span className="section-index">01 — THE RESPONSE QUEUE</span><h2>Behind every signal,<br/><em>someone is waiting.</em></h2></div><button className="text-button" onClick={()=>navigate('Signals')}>All incidents <span>{incidents.length}</span><ArrowUpRight size={20}/></button></div><div className="stream-grid">{unresolved.slice(0,3).map((i,index)=><button className="stream-card" key={i.id} onClick={()=>selectAndReview(i.id)}><div className="stream-card-top"><span className="stream-number">0{index+1}</span><span className={`severity ${i.severity}`}><i/>{i.severity}</span><ArrowUpRight size={18}/></div><h3>{i.title}</h3><div className="stream-card-bottom"><span>{i.location}</span><span>{i.people} people</span></div><div className="stream-hover-line"/></button>)}</div>{!unresolved.length&&<div className="all-resolved"><ShieldCheck size={24}/><p>Every signal has been resolved. The community is ready for what comes next.</p></div>}</section>
  <OperationsDeck incidents={incidents} audit={audit} busy={relay.busy} onReplay={()=>setRehearsalOpen(true)} onSelect={selectAndReview} onInject={async input=>{const id=await relay.report(input);if(id){setSelected(id);navigate('Mission control');}return id;}}/>
  <section className="trust-strip"><div className="trust-emblem"><ShieldCheck size={32}/></div><div><span className="section-index">AUTOMATION WITH A HUMAN AT THE CENTRE</span><h2>Intelligent matching.<br/><em>Accountable action.</em></h2></div><p>A closer team isn’t always the right team. Relay checks skills, capacity, and availability. AWS Cedar evaluates every dispatch. A human makes the call.</p><button aria-label="Inspect the decision log" onClick={()=>navigate('Decisions')}><ArrowUpRight size={27}/></button></section>
  </main>
  <footer className="command-footer"><button className="footer-brand" onClick={()=>navigate('Mission control')}><RelayLogo compact/></button><p>A community response rehearsal.<br/>Built for AWS First Commit · 2026</p><div><button onClick={()=>setDemoOpen(true)}><CircleHelp size={14}/>How Relay works</button><button onClick={relay.exportSnapshot}><Download size={14}/>Export workspace</button><button onClick={()=>setResetOpen(true)}><RotateCcw size={14}/>Reset scenario</button></div><span>MADE FOR THE MOMENTS<br/>THAT MATTER.</span></footer>
  <IncidentIntake open={reportOpen} onOpenChange={setReportOpen} incidents={incidents} busy={relay.busy} onReport={async (i,fusion)=>{const id=await relay.report(i,fusion);if(id)setSelected(id);return id;}}/>
  <ResponseSheet key={`${active.id}-${responseOpen}`} incident={active} incidents={incidents} audit={audit} open={responseOpen} onOpenChange={setResponseOpen} onTransition={relay.transition} busy={relay.busy} engine={relay.engine}/>
  <RehearsalDialog open={rehearsalOpen} onOpenChange={setRehearsalOpen}/>
  <InteractionEffects/>
  <ExperienceSettings open={settingsOpen} onOpenChange={setSettingsOpen} preferences={experience.preferences} onChange={experience.update} onPreview={()=>experience.go(view,true)}/>
  <PageTransition layer={experience.layer} label={experience.layer?viewLabels[experience.layer.target]:''}/>
  <DemoDialog open={demoOpen} onOpenChange={setDemoOpen} onStart={()=>{setDemoOpen(false);navigate('Mission control');setSelected('RLY-1042');setResponseOpen(true);}}/>
  <AlertDialog open={resetOpen} onOpenChange={setResetOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Restore the sample scenario?</AlertDialogTitle><AlertDialogDescription>This replaces this browser’s signals and decision log with the original demo. Export your workspace first if you want a copy. You can undo from the reset notification.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep my workspace</AlertDialogCancel><AlertDialogAction onClick={()=>{relay.reset();setSelected('RLY-1042');}}>Reset scenario</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  <Toaster theme="dark" position="bottom-center" richColors/>
 </div>;
}
