'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, AudioLines, ChevronRight, CircleHelp, CloudRain, Crosshair, Download, Globe2, LayoutGrid, MapPin, Menu, Plus, Radio, RotateCcw, ShieldCheck, Users, X } from 'lucide-react';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { Toaster } from '@/components/ui/sonner';
import { AuditView, DemoDialog, ReportDialog, ResponseSheet, SignalsView, TeamsView } from '@/components/relay-views';
import { useRelay } from '@/hooks/use-relay';
import ResponseField from '@/components/response-field';
import ResponseMap from '@/components/response-map';
import { teams, categoryLabels } from '@/lib/relay';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
type View='Mission control'|'Signals'|'Responders'|'Decisions';

export default function Home(){
 const relay=useRelay(),{incidents,audit}=relay;
 const [view,setView]=useState<View>('Mission control'),[selected,setSelected]=useState('RLY-1042'),[reportOpen,setReportOpen]=useState(false),[responseOpen,setResponseOpen]=useState(false),[demoOpen,setDemoOpen]=useState(false),[resetOpen,setResetOpen]=useState(false),[mapMode,setMapMode]=useState('spatial'),[menuOpen,setMenuOpen]=useState(false);
 const active=incidents.find(i=>i.id===selected)??incidents[0];
 const pending=incidents.filter(i=>i.status==='open'),urgent=pending.filter(i=>i.severity==='critical'),available=teams.filter(t=>!incidents.some(i=>i.status==='dispatched'&&i.teamId===t.id)),unresolved=incidents.filter(i=>i.status!=='resolved'),resolved=incidents.filter(i=>i.status==='resolved');
 const people=unresolved.reduce((n,i)=>n+i.people,0);
 const routeTeam=teams.find(t=>t.id===active.teamId);
 const selectAndReview=(id:string)=>{setSelected(id);setResponseOpen(true);};
 const navigate=(v:View)=>{setView(v);setMenuOpen(false);};
 const stateRef=useRef({incidents,audit});stateRef.current={incidents,audit};
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}};register({name:'read_response_workspace',description:'Read local demo signals, team assignments, and decision count.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({mode:'local-demo',incidents:stateRef.current.incidents,decisionCount:stateRef.current.audit.length})});register({name:'open_signal_review',description:'Open the response review for a signal. Does not dispatch or resolve anything.',inputSchema:{type:'object',properties:{signalId:{type:'string'}},required:['signalId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||!('signalId' in input)||typeof input.signalId!=='string'||!stateRef.current.incidents.some(i=>i.id===input.signalId))throw new Error('Unknown signal ID');setSelected(input.signalId);setResponseOpen(true);return {opened:input.signalId,dispatched:false};}});return ()=>life.abort();},[]);
 const titles:Record<View,{title:string;accent:string;subtitle:string}>={'Mission control':{title:'When every',accent:'second counts.',subtitle:'One clear picture. One coordinated response.'},Signals:{title:'Every call.',accent:'Accounted for.',subtitle:'Find the need. Read the context. Make the connection.'},Responders:{title:'Built around',accent:'the responders.',subtitle:'The right skills. The right capacity. The right people.'},Decisions:{title:'Trust leaves',accent:'a trace.',subtitle:'Real AWS Cedar decisions. Inspectable, explainable, recorded.'}};
 return <div className="relay-experience"><div className="ambient-glow glow-one"/><div className="ambient-glow glow-two"/><div className="film-grain" aria-hidden="true"/>
  <header className="command-header"><button className="brand" aria-label="Relay mission control" onClick={()=>navigate('Mission control')}><span className="brand-symbol"><i/><i/><i/></span>relay<span className="brand-dot">®</span><span className="brand-caption">RESPONSE<br/>INTELLIGENCE</span></button><nav className={menuOpen?'command-nav nav-open':'command-nav'} aria-label="Workspace">{(['Mission control','Signals','Responders','Decisions'] as View[]).map((name,index)=><button key={name} onClick={()=>navigate(name)} className={view===name?'active':''} aria-current={view===name?'page':undefined}><span>0{index+1}</span>{name}{name==='Signals'&&<i>{pending.length}</i>}</button>)}</nav><div className="header-tools"><span className="cedar-badge"><span/>AWS CEDAR</span><button className="header-help" aria-label="Explore the demo" onClick={()=>setDemoOpen(true)}><CircleHelp size={18}/></button><button className="report-top" onClick={()=>setReportOpen(true)} disabled={!relay.ready}><Plus size={15}/><span>Report a signal</span></button><button className="mobile-menu" aria-label={menuOpen?'Close navigation':'Open navigation'} onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X size={22}/>:<Menu size={22}/>}</button></div></header>
  <main>
  {view==='Mission control'?<section className="mission-stage view-enter" key="mission"><div className="stage-corner top-left"/><div className="stage-corner bottom-right"/>
   <div className="mission-intro"><div className="mission-kicker"><span className="status-orbit"/>HUMANITY, COORDINATED<span className="kicker-line"/></div><h1 className="burn-reveal">When every<br/><em>second counts.</em></h1><p>From scattered calls for help<br/>to a city that responds as one.</p><div className="mission-actions"><button className="primary-button" onClick={()=>selectAndReview(pending[0]?.id??active.id)}>Coordinate a response<ArrowUpRight size={18}/></button><button className="watch-demo" onClick={()=>setDemoOpen(true)}><span><ArrowRight size={16}/></span>Explore the demo</button></div><div className="mission-stats"><div><strong key={`u-${urgent.length}`}>{String(urgent.length).padStart(2,'0')}<span className="urgent-spark"/></strong><span>Critical signals</span></div><div><strong key={`p-${people}`}>{people}<span className="stat-unit"> people</span></strong><span>Awaiting resolution</span></div><div><strong key={`t-${available.length}`}>{String(available.length).padStart(2,'0')}</strong><span>Teams available</span></div></div></div>
   <div className="scene-shell"><div className="scene-halo"/>{mapMode==='spatial'?<ResponseField incidents={incidents} selected={active.id} onSelect={selectAndReview}/>:<div className="geographic-stage"><ResponseMap incidents={incidents} teams={available} selected={active.id} onSelect={selectAndReview} route={active.status==='dispatched'&&routeTeam?{team:routeTeam,incident:active}:undefined}/></div>}</div>
   <div className="scene-location"><div><span className="coordinate-cross">+</span><span>BENGALURU, IN</span><Globe2 size={14}/></div><p>12.9450° N&nbsp;&nbsp;77.6300° E</p><span className="scenario-pill"><CloudRain size={13}/>MONSOON / SAMPLE SCENARIO</span></div>
   <div className="scene-caption"><div className="scene-caption-line"/><span>{mapMode==='spatial'?'SPATIAL RESPONSE FIELD':'GEOGRAPHIC RESPONSE MAP'}</span><p>{mapMode==='spatial'?'Height represents priority. Not terrain or flood depth.':'Approximate neighbourhood locations. Not navigation.'}</p></div>
   <div className="scene-mode"><Tabs value={mapMode} onValueChange={setMapMode}><TabsList><TabsTrigger value="spatial"><AudioLines size={14}/>Spatial</TabsTrigger><TabsTrigger value="map"><MapPin size={14}/>Map</TabsTrigger></TabsList></Tabs></div>
   <div className="focus-dock"><div className="focus-index"><span>FOCUS SIGNAL</span><strong>{String(incidents.findIndex(i=>i.id===active.id)+1).padStart(2,'0')}<span>/ {String(incidents.length).padStart(2,'0')}</span></strong></div><div className="focus-main"><div><span className={`severity ${active.severity}`}><i/>{active.severity} priority</span><span className="focus-code">{active.id}</span></div><h2>{active.title}</h2><p><MapPin size={13}/>{active.location}<span> / </span>{active.people} people<span> / </span>{categoryLabels[active.category]}<span className="focus-status">{active.status==='open'?'Needs a team':active.status==='dispatched'?'Team assigned':'Resolved'}</span></p></div><button className="focus-action" onClick={()=>setResponseOpen(true)}><span>Review response</span><ArrowUpRight size={23}/></button></div>
   <div className="stage-bottom"><span><i/>LOCAL-FIRST. HUMAN-LED. CEDAR-CHECKED.</span><span>NO LIVE EMERGENCY DATA<ArrowDown size={12}/></span></div>
  </section>:<section className="work-surface view-enter" key={view}><div className="work-title"><div><span className="mission-kicker">RELAY / {view.toUpperCase()}</span><h1>{titles[view].title} <em>{titles[view].accent}</em></h1><p>{titles[view].subtitle}</p></div><button className="primary-button" onClick={()=>setReportOpen(true)}><Plus size={16}/>Report a signal</button></div>{view==='Signals'?<SignalsView incidents={incidents} onSelect={selectAndReview}/>:view==='Responders'?<TeamsView incidents={incidents} onSelect={selectAndReview}/>:<AuditView audit={audit} engine={relay.engine} onExport={relay.exportSnapshot}/>}</section>}
  <section className="signal-stream"><div className="stream-heading"><div><span className="section-index">01 — THE RESPONSE QUEUE</span><h2>Behind every signal,<br/><em>someone is waiting.</em></h2></div><button className="text-button" onClick={()=>navigate('Signals')}>All signals <span>{incidents.length}</span><ArrowUpRight size={20}/></button></div><div className="stream-grid">{unresolved.slice(0,3).map((i,index)=><button className="stream-card" key={i.id} onClick={()=>selectAndReview(i.id)}><div className="stream-card-top"><span className="stream-number">0{index+1}</span><span className={`severity ${i.severity}`}><i/>{i.severity}</span><ArrowUpRight size={18}/></div><h3>{i.title}</h3><div className="stream-card-bottom"><span>{i.location}</span><span>{i.people} people</span></div><div className="stream-hover-line"/></button>)}</div>{!unresolved.length&&<div className="all-resolved"><ShieldCheck size={24}/><p>Every signal has been resolved. The community is ready for what comes next.</p></div>}</section>
  <section className="trust-strip"><div className="trust-emblem"><ShieldCheck size={32}/></div><div><span className="section-index">AUTOMATION WITH A HUMAN AT THE CENTRE</span><h2>Intelligent matching.<br/><em>Accountable action.</em></h2></div><p>A closer team isn’t always the right team. Relay checks skills, capacity, and availability. AWS Cedar evaluates every dispatch. A human makes the call.</p><button aria-label="Inspect the decision log" onClick={()=>navigate('Decisions')}><ArrowUpRight size={27}/></button></section>
  </main>
  <footer className="command-footer"><button className="footer-brand" onClick={()=>navigate('Mission control')}>relay<span>®</span></button><p>A community response rehearsal.<br/>Built for AWS First Commit · 2026</p><div><button onClick={relay.exportSnapshot}><Download size={14}/>Export workspace</button><button onClick={()=>setResetOpen(true)}><RotateCcw size={14}/>Reset scenario</button></div><span>MADE FOR THE MOMENTS<br/>THAT MATTER.</span></footer>
  <ReportDialog open={reportOpen} onOpenChange={setReportOpen} busy={relay.busy} onReport={async i=>{const id=await relay.report(i);if(id)setSelected(id);return id;}}/>
  <ResponseSheet key={`${active.id}-${responseOpen}`} incident={active} incidents={incidents} open={responseOpen} onOpenChange={setResponseOpen} onTransition={relay.transition} busy={relay.busy} engine={relay.engine}/>
  <DemoDialog open={demoOpen} onOpenChange={setDemoOpen} onStart={()=>{setDemoOpen(false);navigate('Mission control');setSelected('RLY-1042');setResponseOpen(true);}}/>
  <AlertDialog open={resetOpen} onOpenChange={setResetOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Restore the sample scenario?</AlertDialogTitle><AlertDialogDescription>This replaces this browser’s signals and decision log with the original demo. Export your workspace first if you want a copy. You can undo from the reset notification.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep my workspace</AlertDialogCancel><AlertDialogAction onClick={()=>{relay.reset();setSelected('RLY-1042');}}>Reset scenario</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  <Toaster theme="dark" position="bottom-center" richColors/>
 </div>;
}
