import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { initialIncidents, teams, rankTeams, distanceKm } from '../lib/relay.ts';
import { createAuthorizationRequest, cedarSchema, policies } from '../lib/policy.ts';
const require=createRequire(import.meta.url),cedar=require('@cedar-policy/cedar-wasm/nodejs');
const incident=initialIncidents[0],team=teams[0];
const request=(override:Partial<Parameters<typeof createAuthorizationRequest>[0]>={})=>createAuthorizationRequest({action:'dispatch',role:'coordinator',incident,team,incidents:initialIncidents,confirmed:true,...override});
const decision=(input:ReturnType<typeof request>)=>{const r=cedar.isAuthorized(input);assert.equal(r.type,'success');assert.equal(r.response.diagnostics.errors.length,0);return r.response;};
test('all actual Cedar policies validate against the schema',()=>{const r=cedar.validate({schema:cedarSchema,policies:{staticPolicies:policies}});assert.equal(r.type,'success');assert.deepEqual(r.validationErrors,[]);});
test('coordinator dispatch succeeds with human confirmation and a suitable team',()=>{const r=decision(request());assert.equal(r.decision,'allow');assert.ok(r.diagnostics.reason.includes('coordinator-dispatch'));});
test('volunteer dispatch is forbidden even with explicit confirmation',()=>{const r=decision(request({role:'volunteer'}));assert.equal(r.decision,'deny');assert.ok(r.diagnostics.reason.includes('coordinator-required'));});
test('human confirmation is required',()=>assert.equal(decision(request({confirmed:false})).decision,'deny'));
test('wrong district is denied',()=>assert.equal(decision(request({district:'mysuru'})).decision,'deny'));
test('mismatched team skills and insufficient capacity are denied',()=>{assert.equal(decision(request({team:teams[1]})).decision,'deny');assert.equal(decision(request({team:teams[4]})).decision,'deny');});
test('a busy team cannot be assigned twice',()=>{const incidents=[...initialIncidents,{...initialIncidents[4],id:'busy',status:'dispatched' as const,teamId:team.id}];assert.equal(decision(request({incidents})).decision,'deny');assert.ok(!rankTeams(incident,incidents).find(r=>r.team.id===team.id)?.eligible);});
test('an already dispatched signal cannot receive another team',()=>assert.equal(decision(request({incident:{...incident,status:'dispatched',teamId:team.id}})).decision,'deny'));
test('resolution requires a dispatched signal and a coordinator',()=>{assert.equal(decision(request({action:'resolve'})).decision,'deny');assert.equal(decision(request({action:'resolve',incident:{...incident,status:'dispatched',teamId:team.id}})).decision,'allow');assert.equal(decision(request({action:'resolve',incident:{...incident,status:'dispatched',teamId:team.id},role:'volunteer'})).decision,'deny');});
test('community members can report a local signal',()=>assert.equal(decision(request({action:'report',role:'volunteer'})).decision,'allow'));
test('matching prefers an eligible team over closer unqualified teams',()=>{const r=rankTeams(initialIncidents[4],initialIncidents);assert.equal(r[0].team.id,'t5');assert.equal(r[0].eligible,true);assert.ok(r.some(c=>c.reasons.includes('Required skill does not match')));});
test('oversized incidents produce no unsafe fallback',()=>assert.equal(rankTeams({...incident,people:10000},initialIncidents).filter(t=>t.eligible).length,0));
test('distances are symmetric and zero at the same location',()=>{assert.equal(distanceKm(incident,incident),0);assert.ok(Math.abs(distanceKm(incident,team)-distanceKm(team,incident))<1e-10);});
