'use client';
import { useEffect, useRef } from 'react';
import { ArrowLeft, ArrowRight, ArrowUpRight, MapPin, Radio } from 'lucide-react';
import type { Incident } from '@/lib/relay';
export default function CityAtmosphere({paused,incident,index,total,onPrevious,onNext,onReview}:{paused:boolean;incident:Incident;index:number;total:number;onPrevious:()=>void;onNext:()=>void;onReview:()=>void}){
 const surface=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(paused||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;let frame=0;const move=(event:PointerEvent)=>{if(event.pointerType==='touch')return;cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{surface.current?.style.setProperty('--city-x',`${(event.clientX/window.innerWidth-.5)*-16}px`);surface.current?.style.setProperty('--city-y',`${(event.clientY/window.innerHeight-.5)*-10}px`);});};window.addEventListener('pointermove',move,{passive:true});return ()=>{window.removeEventListener('pointermove',move);cancelAnimationFrame(frame);};},[paused]);
 return <div className={`city-atmosphere ${paused?'city-paused':''}`} ref={surface}><div className="city-image-drift"><img src="/relay-city-night.webp" alt="Illustration of a riverside city under a stormy night sky" fetchPriority="high"/></div><div className="city-color-wash"/><div className="city-reflection"/><div className="city-signal-card"><div className="city-card-heading"><span><Radio size={13}/>COMMUNITY INCIDENT</span><span>{String(index+1).padStart(2,'0')} / {String(total).padStart(2,'0')}</span></div><div key={incident.id} className="city-card-story"><span className={`severity ${incident.severity}`}><i/>{incident.severity} priority</span><h3>{incident.title}</h3><p><MapPin size={13}/>{incident.location}<span>·</span>{incident.people} people</p><button onClick={onReview}>Review this incident<ArrowUpRight size={17}/></button></div><div className="city-card-controls"><span>Fictional reports · illustrative city</span><button aria-label="Previous incident" onClick={onPrevious}><ArrowLeft size={14}/></button><button aria-label="Next incident" onClick={onNext}><ArrowRight size={14}/></button></div></div><span className="city-atmosphere-caption">A CITY WORTH SHOWING UP FOR.</span></div>;
}
