'use client';
import { createPortal } from 'react-dom';
import './page-transitions.css';
import { Check, Flame, Layers, Volume2, Waves } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Switch } from '@/components/ui/switch';
import type { ExperiencePreferences, TransitionStyle } from '@/hooks/use-experience';
const styles:{id:TransitionStyle;label:string;description:string;icon:typeof Waves}[]=[{id:'wave',label:'Tidal wave',description:'A fluid sweep between views.',icon:Waves},{id:'ember',label:'Light dissolve',description:'A fine light edge reveals the next view.',icon:Flame},{id:'fade',label:'Soft fade',description:'A quiet crossfade with depth.',icon:Layers}];
export function ExperienceSettings({open,onOpenChange,preferences,onChange,onPreview}:{open:boolean;onOpenChange:(v:boolean)=>void;preferences:ExperiencePreferences;onChange:(v:Partial<ExperiencePreferences>)=>void;onPreview:()=>void}){return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="relay-dialog experience-dialog"><DialogHeader><span className="eyebrow">MAKE IT YOURS</span><DialogTitle>Set the atmosphere.</DialogTitle><DialogDescription>Subtle sound. Expressive motion. Always in your control.</DialogDescription></DialogHeader><div className="experience-option"><div><h3><Volume2 size={17}/>Interface sounds</h3><p>Soft taps, flowing transitions and decision chimes.</p></div><Switch checked={preferences.sound} onCheckedChange={sound=>onChange({sound})} aria-label="Interface sounds"/></div><div className="experience-option"><div><h3><Waves size={17}/>Ambient motion</h3><p>Animate the waves, logo, city, and page transitions.</p></div><Switch checked={preferences.motion} onCheckedChange={motion=>onChange({motion})} aria-label="Ambient motion"/></div><fieldset className="transition-choices"><legend>Moving between pages</legend>{styles.map(s=><button type="button" key={s.id} aria-pressed={preferences.transition===s.id} onClick={()=>onChange({transition:s.id})}><span className={`transition-swatch swatch-${s.id}`}><s.icon size={22}/></span><span><strong>{s.label}</strong><small>{s.description}</small></span>{preferences.transition===s.id&&<Check size={18}/>}</button>)}</fieldset><button className="primary-button full-width" onClick={onPreview}>Preview this transition<Layers size={16}/></button><p className="form-hint">Sound starts only when you turn it on. Your device’s reduced-motion setting takes priority.</p></DialogContent></Dialog>;}
export function PageTransition({layer,label}:{layer:{id:number;style:TransitionStyle;phase:'cover'|'reveal'}|null;label:string}){if(!layer||typeof document==='undefined')return null;return createPortal(<div className={`page-transition transition-${layer.style} transition-${layer.phase}`} key={layer.id} aria-hidden="true"><div className="transition-curtain"><svg className="transition-crest" viewBox="0 0 1440 150" preserveAspectRatio="none"><path className="crest-back" d="M0 100C240 0 350 150 600 80S1100 0 1440 90V150H0Z"/><path d="M0 110C200 150 400 10 720 90S1200 140 1440 65V150H0Z"/></svg><div className="transition-destination"><Waves size={30}/><span>RELAY</span><strong>{label}</strong></div></div><div className="ember-edge"/></div>,document.body); }
