'use client';
import { Check, Fingerprint, GitMerge, Radio, ShieldCheck } from 'lucide-react';
import { categoryLabels, rankTeams, type Incident, type Audit } from '@/lib/relay';

export function ResponsePipeline({incident,confirmed,result,matched,onStep}:{incident:Incident;confirmed:boolean;result?:'Allow'|'Deny';matched:boolean;onStep:(v:'response'|'evidence'|'timeline')=>void}){
 const acted=incident.status!=='open';const complete=[true,matched,result==='Allow'||acted,confirmed||acted,!!result||acted];
 return <div className="response-pipeline" aria-label="Response workflow">{['Signal','Team fit','Cedar','Human','Audit'].map((label,n)=><button key={label} className={`${complete[n]?'complete':''} ${n===2&&result==='Deny'?'blocked':''}`} onClick={()=>onStep(n===0?'evidence':n===4?'timeline':'response')}><span>{complete[n]?<Check size={12}/>:String(n+1).padStart(2,'0')}</span><small>{label}</small></button>)}</div>;
}
export function IncidentEvidence({incident}:{incident:Incident}){return <section className="intel-panel chapter-transition"><div className="intel-title"><Fingerprint size={24}/><div><span className="eyebrow">EVIDENCE, NOT ASSUMPTIONS</span><h3>{1+(incident.reports?.length??0)} account{incident.reports?.length?'s':''}. One incident.</h3></div></div><div className="evidence-status"><span>Source status</span><strong>Unverified community report</strong><p>Multiple reports add context; they do not establish credibility. A coordinator must verify the situation.</p></div><article className="evidence-account"><span>01 / ORIGINAL ACCOUNT</span><p>{incident.description}</p><small>{incident.source} · Original headcount: {incident.originalReport?.people??incident.people} · Original priority: {incident.originalReport?.severity??incident.severity}</small></article>{incident.reports?.map((r,n)=><article key={r.id} className="evidence-account"><span><GitMerge size={13}/>0{n+2} / SUPPORTING ACCOUNT</span><p>{r.text}</p><small>Reported headcount: {r.people} · {new Date(r.reportedAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</small></article>)}{incident.evidence?.length?<div className="extraction-quotes"><h4>Text cues from initial triage</h4>{incident.evidence.map((e,n)=><p key={n}><Check size={13}/>{e}</p>)}<small>The final fields may have been edited during review.</small></div>:null}</section>;}
export function IncidentTimeline({incident,audit}:{incident:Incident;audit:Audit[]}){
 const events=audit.filter(e=>e.incidentId===incident.id).slice().reverse();
 return <section className="intel-panel chapter-transition"><div className="intel-title"><Radio size={23}/><div><span className="eyebrow">THE INCIDENT, UNFOLDED</span><h3>A trace of every decision.</h3></div></div><ol className="incident-timeline"><li><span className="timeline-node"><Radio size={15}/></span><div><time>{new Date(incident.createdAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</time><h4>Signal received</h4><p>{categoryLabels[incident.category]} · {incident.location} · {incident.source}</p></div></li>{events.map(e=><li key={e.id}><span className={`timeline-node ${e.outcome.toLowerCase()}`}><ShieldCheck size={15}/></span><div><time>{new Date(e.time).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time><h4>{e.action}<b className={e.outcome.toLowerCase()}>{e.outcome}</b></h4><p>{e.detail}</p>{e.policy&&<code>{e.policy}</code>}</div></li>)}</ol><div className="timeline-present"><span/>CURRENT STATE<strong>{incident.status==='open'?'Awaiting assignment':incident.status==='dispatched'?'Team responding':'Response completed'}</strong></div><p className="form-hint">Shows linked events retained in this browser, up to the latest 1,000 workspace decisions. Older demo events without a signal link remain in Decisions.</p></section>;
}
