'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, GitMerge, LoaderCircle, ScanLine, Sparkles, Radio, ShieldCheck } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Checkbox } from '@/components/ui/checkbox';
import { triageReport, duplicateCandidates, reportExamples, type TriageDraft } from '@/lib/triage';
import { categoryLabels, neighborhoods, type Category, type Severity, type Incident, type ReportInput } from '@/lib/relay';

export default function IncidentIntake({open,onOpenChange,incidents,busy,onReport}:{open:boolean;onOpenChange:(v:boolean)=>void;incidents:Incident[];busy:boolean;onReport:(i:ReportInput,fusion?:{targetId:string;confirmed:boolean})=>Promise<string|false>}){
 const [phase,setPhase]=useState<'write'|'scan'|'review'>('write'),[text,setText]=useState(''),[draft,setDraft]=useState<TriageDraft|null>(null),[location,setLocation]=useState(''),[category,setCategory]=useState(''),[severity,setSeverity]=useState<Severity>('high'),[people,setPeople]=useState(''),[title,setTitle]=useState(''),[target,setTarget]=useState(''),[confirmed,setConfirmed]=useState(false),[error,setError]=useState('');
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 useEffect(()=>{if(!open&&timer.current){clearTimeout(timer.current);setPhase('write');}},[open]);
 function analyze(){if(text.trim().length<10){setError('Describe the situation in at least 10 characters.');return;}setError('');setPhase('scan');setConfirmed(false);setTarget('');const parsed=triageReport(text);timer.current=setTimeout(()=>{setDraft(parsed);setLocation(parsed.location??'');setCategory(parsed.category??'');setSeverity(parsed.severity);setPeople(parsed.people===null?'':String(parsed.people));setTitle(parsed.title);setPhase('review');},850);}
 const candidates=location&&category?duplicateCandidates({title,description:text,location,category:category as Category},incidents):[];
 const chosen=candidates.find(c=>c.incident.id===target);
 async function submit(e:React.FormEvent){e.preventDefault();if(!confirmed){setError('Review the suggested fields and confirm before continuing.');return;}const place=neighborhoods.find(p=>p.name===location);if(!place||!category||people===''||!Number.isInteger(Number(people))||Number(people)<0||Number(people)>10000){setError('Confirm the neighbourhood, support type, and a headcount between 0 and 10,000.');return;}if(target&&!chosen){setError('That incident changed. Review the current suggestions.');setTarget('');return;}
 const id=await onReport({title,description:text,location,category:category as Category,severity,people:Number(people),lat:place.lat,lng:place.lng,evidence:draft?.evidence},chosen?{targetId:chosen.incident.id,confirmed}:undefined);if(id){setText('');setDraft(null);setPhase('write');setConfirmed(false);onOpenChange(false);}}
 return <Dialog open={open} onOpenChange={v=>{if(!busy)onOpenChange(v);}}><DialogContent className="relay-dialog intake-dialog"><DialogHeader><div className="intake-heading"><span className="dialog-icon"><ScanLine size={25}/></span><span className="intake-step">INCIDENT INTAKE / {phase==='write'?'01':phase==='scan'?'02':'03'}</span></div><DialogTitle>{phase==='write'?'Start with what happened.':phase==='scan'?'Finding the signal.':'A clearer picture. Your call.'}</DialogTitle><DialogDescription>{phase==='write'?'Turn a scattered report into a coordinated response. Use fictional details for this rehearsal.':phase==='scan'?'Reading location, support cues, and the reported headcount.':'Check the extracted fields. Suggestions are unverified until you review them.'}</DialogDescription></DialogHeader>
 <div key={phase} className="intake-stage chapter-transition">
 {phase==='write'&&<><label className="intake-label" htmlFor="distress-report">Describe the situation</label><textarea id="distress-report" className="narrative-input" placeholder="12 residents are stranded by rising water in Bellandur. A boat is needed…" value={text} maxLength={2000} onChange={e=>setText(e.target.value)}/><div className="narrative-meta"><span>Plain language. No perfect form required.</span><span>{text.length}/2,000</span></div><div className="example-presets"><span>TRY A SAMPLE</span>{reportExamples.map(example=><button key={example.label} onClick={()=>{setText(example.text);setError('');}}><Sparkles size={13}/>{example.label}</button>)}</div><button className="primary-button full-width" onClick={analyze} disabled={text.trim().length<10}><ScanLine size={18}/>Analyze this report<ArrowRight size={18}/></button><p className="local-disclosure compact">Local language rules · no AI model connected · nothing sent to a server</p></>}
 {phase==='scan'&&<div className="triage-scanner" role="status"><div className="scanner-orbit"><ScanLine size={42}/></div><div className="scanner-beam"/>{['Locate the neighbourhood','Extract support and urgency cues','Find a reported headcount','Compare existing open incidents'].map((s,n)=><p key={s} style={{animationDelay:`${n*160}ms`}}><Check size={14}/>{s}</p>)}</div>}
 {phase==='review'&&draft&&<form onSubmit={submit} className="report-form"><div className="extraction-status"><span><Check size={15}/>{draft.evidence.length} text cues found</span><span>{draft.missing.length?'Review needed':'Ready for review'}</span></div><div className="extracted-fields"><label>Incident title<input value={title} onChange={e=>{setTitle(e.target.value);setConfirmed(false);}} minLength={4} maxLength={100} required/></label><div className="form-row"><label>Neighbourhood<select value={location} onChange={e=>{setLocation(e.target.value);setConfirmed(false);setTarget('');}} required><option value="">Choose a neighbourhood</option>{neighborhoods.map(p=><option key={p.name}>{p.name}</option>)}</select></label><label>Support needed<select value={category} onChange={e=>{setCategory(e.target.value);setConfirmed(false);setTarget('');}} required><option value="">Choose support</option>{Object.entries(categoryLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label></div><div className="form-row"><label>Priority<select value={severity} onChange={e=>{setSeverity(e.target.value as Severity);setConfirmed(false);}}><option value="critical">Critical</option><option value="high">High</option><option value="moderate">Moderate</option></select></label><label>People affected<input type="number" value={people} min={0} max={10000} step={1} required placeholder="Confirm headcount" onChange={e=>{setPeople(e.target.value);setConfirmed(false);}}/></label></div></div>
 <details className="triage-evidence" open={draft.missing.length>0}><summary><Sparkles size={15}/>Why these suggestions?<span>{draft.evidence.length} cues</span></summary><div>{draft.evidence.map(quote=><p key={quote}>{quote}</p>)}{draft.missing.map(m=><p className="review-warning" key={m}>{m}</p>)}<small>Text extraction is not a credibility score. Always verify on the ground.</small></div></details>
 {candidates.length>0&&<fieldset className="fusion-panel"><legend><GitMerge size={16}/>This may already be on our radar.</legend><p>Similar wording, same support type and neighbourhood. Choose deliberately; similarity does not prove a duplicate.</p>{candidates.slice(0,3).map(c=><label className={`fusion-option ${target===c.incident.id?'chosen':''}`} key={c.incident.id}><input type="radio" name="fusion" value={c.incident.id} checked={target===c.incident.id} onChange={()=>{setTarget(c.incident.id);setConfirmed(false);}}/><span><strong>{c.incident.title}</strong><small>{c.incident.id} · {1+(c.incident.reports?.length??0)} report(s) · {c.incident.people} people</small></span><GitMerge size={17}/></label>)}<label className="fusion-separate"><input type="radio" name="fusion" checked={!target} onChange={()=>{setTarget('');setConfirmed(false);}}/>This is a separate incident</label>{chosen&&<p className="fusion-note">Both accounts stay in the evidence. Headcount becomes {Math.max(chosen.incident.people,Number(people)||0)}, the higher estimate, never a sum. Priority cannot decrease. Coordinator confirmation is checked by Cedar.</p>}</fieldset>}
 <label className="confirmation"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/><span>{chosen?'As demo coordinator, I confirm these reports describe the same incident and have reviewed the retained headcount.':'I have reviewed the location, support type, priority, and headcount.'}</span></label><div className="intake-actions"><button className="secondary-button" type="button" disabled={busy} onClick={()=>setPhase('write')}><ArrowLeft size={16}/>Edit report</button><button className="primary-button" disabled={busy||!confirmed} type="submit">{busy?<LoaderCircle size={17} className="animate-spin"/>:chosen?<GitMerge size={17}/>:<Radio size={17}/>} {chosen?'Combine reports':'Publish incident'}<ArrowRight size={17}/></button></div></form>}
 {error&&<p className="form-error" role="alert">{error}</p>}
 </div></DialogContent></Dialog>;
}
