'use client';
import { useState } from 'react';
import { ArrowRight, ArrowUpRight, Check, CheckCircle2, ChevronRight, Download, Heart, MapPin, Radio, Search, ShieldCheck, Users, Waves, Zap, CircleX, Clock3, LoaderCircle, RotateCcw, FileJson, LockKeyhole } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { categoryLabels, neighborhoods, teams, rankTeams, type Incident, type Category, type Severity, type Audit } from '@/lib/relay';
import { policyDescriptions, policies, type Role } from '@/lib/policy';
import type { PolicyDecision } from '@/lib/cedar';
const iconFor={rescue:Waves,medical:Heart,supplies:Users,infrastructure:Zap};
export function SignalCard({incident:i,selected,onClick}:{incident:Incident;selected?:boolean;onClick:()=>void}){const Icon=iconFor[i.category];return <button className={`signal-card ${selected?'is-selected':''}`} onClick={onClick}><div className="signal-card-top"><span className={`severity ${i.severity}`}><i/>{i.severity}</span><span className="signal-id">{i.id}</span></div><h3>{i.title}</h3><div className="signal-meta"><span><MapPin size={13}/>{i.location}</span><span>{i.people} people</span></div><div className="signal-card-bottom"><span><Icon size={13}/>{categoryLabels[i.category]}</span>{i.status==='open'?<ArrowUpRight size={15}/>:<span className={`status-label ${i.status}`}>{i.status==='dispatched'?'Team assigned':'Resolved'}<Check size={12}/></span>}</div></button>;}
export function SignalsView({incidents,onSelect}:{incidents:Incident[];onSelect:(id:string)=>void}){
 const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[category,setCategory]=useState('all');
 const shown=incidents.filter(i=>(status==='all'||i.status===status)&&(category==='all'||i.category===category)&&`${i.title} ${i.location} ${i.id}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="view-enter"><div className="view-toolbar"><div className="search-field"><Search size={17}/><Input aria-label="Search signals" placeholder="Search by need, location, or ID…" value={query} onChange={e=>setQuery(e.target.value)}/></div><Select value={category} onValueChange={setCategory}><SelectTrigger aria-label="Filter category"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All categories</SelectItem>{Object.entries(categoryLabels).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div><Tabs value={status} onValueChange={setStatus}><TabsList className="workspace-tabs">{[['all','All signals'],['open','Needs a team'],['dispatched','Responding'],['resolved','Resolved']].map(([v,l])=><TabsTrigger value={v} key={v}>{l}<span>{incidents.filter(i=>v==='all'||i.status===v).length}</span></TabsTrigger>)}</TabsList></Tabs><div className="signals-grid">{shown.map(i=><SignalCard key={i.id} incident={i} onClick={()=>onSelect(i.id)}/>)}</div>{!shown.length&&<div className="empty-state"><Radio/><h3>No signals here.</h3><p>Try another search or status filter.</p><button className="secondary-button" onClick={()=>{setQuery('');setStatus('all');setCategory('all');}}>Clear filters</button></div>}</div>;
}
export function TeamsView({incidents,onSelect}:{incidents:Incident[];onSelect:(id:string)=>void}){return <div className="view-enter"><div className="view-intro"><ShieldCheck size={19}/><p>Teams are matched by skill, available capacity, and straight-line distance. Assignments require a coordinator’s confirmation.</p></div><div className="teams-grid">{teams.map(t=>{const assignment=incidents.find(i=>i.teamId===t.id&&i.status==='dispatched');const Icon=iconFor[t.skill];return <article className="team-card" key={t.id}><div className="team-card-head"><span className="team-avatar" style={{background:t.color}}>{t.initials}</span><span className={`team-status ${assignment?'busy':''}`}><i/>{assignment?'Responding':'Available'}</span></div><h2>{t.name}</h2><p><Icon size={15}/>{categoryLabels[t.skill]} specialists</p><div className="team-facts"><div><strong>{t.members}</strong><span>Team members</span></div><div><strong>{t.capacity}</strong><span>People per response</span></div></div><div className="team-assignment">{assignment?<><span>Responding in {assignment.location}</span><button onClick={()=>onSelect(assignment.id)} aria-label={`View ${t.name} assignment`}><ArrowUpRight size={18}/></button></>:<span>Ready for a matching signal</span>}</div></article>;})}</div></div>;}
export function AuditView({audit,engine,onExport}:{audit:Audit[];engine:string;onExport:()=>void}){return <div className="view-enter"><div className="audit-banner"><span className="policy-logo"><ShieldCheck size={27}/></span><div><h2>Every decision leaves a trace.</h2><p>{engine} · Real policy evaluation, running on this device.</p></div><button className="secondary-button" onClick={onExport}><Download size={15}/>Export log</button></div><p className="local-disclosure">This local demo evaluates real AWS Cedar policies in your browser. Demo roles are switchable; this is not authenticated, server-enforced access control.</p><div className="audit-list">{audit.map(a=><article className="audit-entry" key={a.id}><span className={`audit-outcome ${a.outcome.toLowerCase()}`}>{a.outcome==='Deny'?<CircleX size={18}/>:<ShieldCheck size={18}/>}</span><div><div className="audit-entry-title"><h3>{a.action}</h3><span>{a.outcome}</span></div><p>{a.detail}</p>{a.policy&&<code>{a.policy}</code>}<time dateTime={a.time}>{new Date(a.time).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'medium'})}</time></div></article>)}</div>{!audit.length&&<div className="empty-state"><ShieldCheck/><h3>Your decision log starts here.</h3><p>Report a signal or review a response to see Cedar’s real decisions.</p></div>}<details className="policy-source"><summary>Inspect the policies <ChevronRight size={16}/></summary>{Object.entries(policies).map(([id,source])=><div key={id}><h3>{id}</h3><pre>{source}</pre></div>)}</details></div>;}
export function ReportDialog({open,onOpenChange,onReport,busy}:{open:boolean;onOpenChange:(v:boolean)=>void;onReport:(i:Omit<Incident,'id'|'createdAt'|'status'|'source'|'district'>)=>Promise<string|false>;busy:boolean}){
 const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[location,setLocation]=useState('Bellandur'),[category,setCategory]=useState<Category>('rescue'),[severity,setSeverity]=useState<Severity>('high'),[people,setPeople]=useState('1'),[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();if(title.trim().length<4||description.trim().length<10){setError('Add a title of at least 4 characters and a description of at least 10 characters.');return;}const n=Number(people);if(!people||!Number.isInteger(n)||n<0||n>10000){setError('Enter a whole number from 0 to 10,000.');return;}const place=neighborhoods.find(p=>p.name===location)!;setError('');const id=await onReport({title,description,category,severity,people:n,location,lat:place.lat,lng:place.lng});if(id){setTitle('');setDescription('');setPeople('1');onOpenChange(false);}}
 return <Dialog open={open} onOpenChange={v=>{if(!busy)onOpenChange(v);}}><DialogContent className="relay-dialog report-dialog"><DialogHeader><span className="dialog-icon"><Radio size={23}/></span><DialogTitle>Someone needs a hand.</DialogTitle><DialogDescription>Add a community signal to this local workspace. Use sample information for this demo.</DialogDescription></DialogHeader><form onSubmit={submit} className="report-form"><label>What’s needed?<Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Drinking water for the community hall" required minLength={4} maxLength={100}/></label><div className="form-row"><div><label id="location-label">Neighbourhood</label><Select value={location} onValueChange={setLocation}><SelectTrigger aria-labelledby="location-label"><SelectValue/></SelectTrigger><SelectContent>{neighborhoods.map(p=><SelectItem key={p.name} value={p.name}>{p.name}</SelectItem>)}</SelectContent></Select></div><div><label id="category-label">Support needed</label><Select value={category} onValueChange={v=>setCategory(v as Category)}><SelectTrigger aria-labelledby="category-label"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(categoryLabels).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div></div><div className="form-row"><div><label id="severity-label">Priority</label><Select value={severity} onValueChange={v=>setSeverity(v as Severity)}><SelectTrigger aria-labelledby="severity-label"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="critical">Critical</SelectItem><SelectItem value="high">High</SelectItem><SelectItem value="moderate">Moderate</SelectItem></SelectContent></Select></div><label>People affected<Input type="number" min="0" max="10000" step="1" value={people} onChange={e=>setPeople(e.target.value)} required/></label></div><label>What should the team know?<Textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe the need, access conditions, and useful context. Avoid personal information." required minLength={10} maxLength={2000} rows={4}/></label><p className="form-hint">Map placement uses the neighbourhood centre. Reports are saved on this browser only.</p>{error&&<p role="alert" className="form-error">{error}</p>}<button type="submit" className="primary-button full-width" disabled={busy}>{busy?<LoaderCircle className="animate-spin" size={17}/>:<Radio size={17}/>}Add signal</button></form></DialogContent></Dialog>;
}
export function ResponseSheet({incident,incidents,open,onOpenChange,onTransition,busy,engine}:{incident:Incident;incidents:Incident[];open:boolean;onOpenChange:(v:boolean)=>void;onTransition:(id:string,action:'dispatch'|'resolve',role:Role,confirmed:boolean,teamId?:string)=>Promise<PolicyDecision|undefined>;busy:boolean;engine:string}){
 const [role,setRole]=useState<Role>('coordinator'),[confirmed,setConfirmed]=useState(false),[result,setResult]=useState<PolicyDecision>();
 const ranked=rankTeams(incident,incidents),best=ranked.find(r=>r.eligible),assigned=teams.find(t=>t.id===incident.teamId);
 const action=incident.status==='dispatched'?'resolve':'dispatch';
 async function run(){const r=await onTransition(incident.id,action,role,confirmed,action==='resolve'?incident.teamId:best?.team.id);setResult(r);if(r?.allowed)setConfirmed(false);}
 return <Sheet open={open} onOpenChange={v=>{if(!busy)onOpenChange(v);}}><SheetContent className="response-sheet"><SheetHeader><div className="sheet-eyebrow"><Radio size={15}/>{incident.id}<span className={`severity ${incident.severity}`}><i/>{incident.severity}</span></div><SheetTitle>{incident.title}</SheetTitle><SheetDescription><MapPin size={15}/>{incident.location}<span>·</span>{incident.people} people<span>·</span>{categoryLabels[incident.category]}</SheetDescription></SheetHeader><div className="sheet-body"><section className="incident-context"><span className="eyebrow">THE SIGNAL</span><p>{incident.description}</p><small>{incident.source} · Sample / local report</small></section>
 {incident.status==='open'&&<><div className="match-title"><span className="eyebrow">THE RIGHT PEOPLE, FOR THE RIGHT REASON</span><ShieldCheck size={17}/></div>{best?<div className="best-match"><div className="best-match-head"><span className="team-avatar" style={{background:best.team.color}}>{best.team.initials}</span><div><small>RECOMMENDED TEAM</small><h3>{best.team.name}</h3></div><CheckCircle2 size={22}/></div><div className="match-reasons"><span><Check size={14}/>{categoryLabels[best.team.skill]} trained</span><span><Check size={14}/>Capacity for {best.team.capacity} people</span><span><Check size={14}/>Available in this district</span></div><div className="match-distance"><strong>{best.distance.toFixed(1)} km <span>straight-line distance</span></strong><span>~{best.eta} min estimate</span></div><p className="estimate-note">Illustrative estimate: 18 km/h + 4-minute mobilisation. Not a road route or verified arrival time.</p></div>:<div className="no-match"><CircleX size={23}/><h3>No suitable team is available.</h3><p>All teams are busy, lack the required skill, or have insufficient capacity. No unsafe fallback is assigned.</p></div>}
 <details className="candidate-details"><summary>Why not another team?<ChevronDownIcon/></summary>{ranked.filter(r=>r.team.id!==best?.team.id).map(r=><div className="candidate" key={r.team.id}><div><strong>{r.team.name}</strong><span>{r.distance.toFixed(1)} km away</span></div><p>{r.eligible?'Eligible, but farther from this signal.':r.reasons.join(' · ')}</p></div>)}</details></>}
 {incident.status==='dispatched'&&<div className="dispatched-card"><span className="success-orbit"><CheckCircle2 size={30}/></span><h3>A response is on its way.</h3><p>{assigned?.name} is assigned to this signal.</p><span>Assignment is simulated; no real team has been contacted.</span></div>}
 {incident.status==='resolved'&&<div className="dispatched-card"><span className="success-orbit"><Heart size={30}/></span><h3>One less need unanswered.</h3><p>This signal is resolved. {assigned?.name??'The team'} is available again.</p></div>}
 {incident.status!=='resolved'&&<section className="decision-controls"><div className="control-title"><LockKeyhole size={17}/><h3>People stay in control.</h3></div><label id="role-label">Demo role</label><Select value={role} onValueChange={v=>{setRole(v as Role);setResult(undefined);}}><SelectTrigger aria-labelledby="role-label"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="coordinator">Coordinator · can dispatch</SelectItem><SelectItem value="volunteer">Volunteer · reports only</SelectItem></SelectContent></Select><label className="confirmation"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/><span>{action==='dispatch'?'I have reviewed the team fit and confirm this assignment.':'I confirm this response is complete and the team can be released.'}</span></label><button className="primary-button full-width" disabled={busy||(action==='dispatch'&&!best)} onClick={run}>{busy?<LoaderCircle className="animate-spin" size={17}/>:<ShieldCheck size={17}/>} {action==='dispatch'?'Confirm & dispatch':'Mark response resolved'}<ArrowRight size={16}/></button><p className="form-hint">Every attempt is evaluated by AWS Cedar and recorded. Try the volunteer role to see a denied action.</p></section>}
 {result&&<div className={`policy-result ${result.allowed?'allowed':'denied'}`} role="status"><div><ShieldCheck size={19}/><strong>Cedar decision: {result.decision}</strong><span>{result.durationMs.toFixed(1)} ms</span></div>{result.reasons.map(reason=><p key={reason}>{policyDescriptions[reason]??reason}<code>{reason}</code></p>)}{result.errors.map((e,i)=><p key={i}>{e}</p>)}<small>Engine {result.version} · Evaluated on this device</small></div>}
 </div><div className="sheet-footer"><ShieldCheck size={15}/>{engine}<span>Local policy demo</span></div></SheetContent></Sheet>;
}
function ChevronDownIcon(){return <ChevronRight className="details-chevron" size={16}/>;}
export function DemoDialog({open,onOpenChange,onStart}:{open:boolean;onOpenChange:(v:boolean)=>void;onStart:()=>void}){return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="relay-dialog demo-dialog"><DialogHeader><span className="dialog-icon"><Waves size={25}/></span><span className="eyebrow">MEET RELAY</span><DialogTitle>From a signal to someone showing up.</DialogTitle><DialogDescription>A hands-on, local demonstration of community response.</DialogDescription></DialogHeader><div className="demo-steps">{[['01','Start with a real need','Twelve sample residents in Bellandur need a rescue team.'],['02','See the reasoning','Compare skills, capacity, availability, and distance.'],['03','Put the policy to the test','Try a volunteer dispatch. Cedar blocks it. Then confirm as a coordinator.'],['04','Close the loop','Resolve the response, release the team, and inspect the decision log.']].map(([n,t,p])=><div key={n}><span>{n}</span><div><h3>{t}</h3><p>{p}</p></div></div>)}</div><p className="local-disclosure">Fictional incidents and teams. No emergency services are contacted. Data stays in this browser; map tiles and fonts use the internet.</p><button className="primary-button full-width" onClick={onStart}>Explore the Bellandur signal<ArrowRight size={17}/></button></DialogContent></Dialog>;}
